version: '3'
services:
  boot-node:
    image: ethereumex/bootnode-registrar:node
    hostname: ${HOST_NAME}-b
    restart: always
    volumes:
      - /home/${USERNAME}/eth-node/.geth:/home/eth-node/.geth
    depends_on:
      - ethereum-node
    environment:
      - INSTANCE_NAME=${HOST_NAME}
      - NODE_NAME=${HOST_NAME}
      - HOST_IP=${HOST_IP}
      - BOOTNODE_URL=${BOOTNODE_URL}
      - BOOTNODE_NETWORK=${BOOTNODE_NETWORK}
      - BOOTNODE_PUBLIC_IP=${BOOTNODE_PUBLIC_IP}
      - ETH_IPC_PATH=/home/eth-node/.geth/geth.ipc
    entrypoint:
      - node
      - client.js
  ethereum-explorer:
    image: jpoon/etherchain-light:0.0.1
    depends_on:
      - ethereum-node
    environment:
      - blockchain_address=http://ethereum-node:8545
    ports:
      - 80:3000
  ethereum-node:
    image: ${DOCKER_IMAGE}
    hostname: ${HOST_NAME}-c
    restart: always
    ipc: host
    privileged: true
    environment:
      - INSTANCE_NAME=${HOST_NAME}
      - NODE_NAME=${HOST_NAME}
      - HOST_IP=${HOST_IP}      
      - NETWORKID=${NETWORK_ID}
      - BOOTNODE_URL=${BOOTNODE_URL}
      - BOOTNODE_NETWORK=${BOOTNODE_NETWORK}
      - ENABLE_MINER=${ENABLE_MINER}
      - MINER_ADDRESS=${MINER_ADDRESS}
      - MINER_THREADS=${MINER_THREADS}
      - EXTERNAL_ARGS=--ethstats ${HOST_NAME}:${WS_SECRET}@${WS_SERVER} ${EXTERNAL_ARGS}
    volumes:
      - /home/${USERNAME}/eth-node/.geth:/home/eth-node/.geth
      - /home/${USERNAME}/eth-node/genesis.json:/home/eth-node/genesis.json
    ports:
      - "30303:30303"
      - "30303:30303/udp"
      - "8545:8545"
      - "8546:8546"
